language: python
dist: xenial
sudo: required
python:
 - "3.7"
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['bash', 'coreutils']
cache:
  directories:
    - /home/travis/.cache/pip
before_install:
  - pip install pipenv==2018.11.26
jobs:
  include:
    - stage: Unit Tests
      script:
        - python setup.py test

